server:
  port: 8111

spring:
#  security:
#    user:
#      name: bob
#      password: 123
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_security?serverTimezone=GMT%2B8
    username: root
    password: qwe123
